# Production domain
baseurl = "https://vantalens.com/"
theme = "stack"
languageCode = "en-us"
title = "Vantalens"

defaultContentLanguage = "zh-cn"

hasCJKLanguage = true

[pagination]
pagerSize = 3
disableAliases = false
path = 'page'

[minify]
  disableXML = true
  minifyOutput = true
